# -*- coding: utf-8 -*-
#
# Copyright (c) 2015 Parisson SARL

# This file is part of Telemeta.

# TimeSide is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.

# TimeSide is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with TimeSide.  If not, see <http://www.gnu.org/licenses/>.

# Authors:
# Guillaume Pellerin <yomguy@parisson.com>
# Thomas Fillon <thomas@parisson.com>


media:
  image: debian:jessie
  volumes:
     - ./media/:/srv/media
     - ./static/:/srv/static
     - ./backup/:/srv/backup
  command: "true"

db:
  image: mysql
  volumes:
    - ./app/deploy/my.cnf:/etc/mysql/my.cnf
    - ./var/lib/mysql/:/var/lib/mysql
  volumes_from:
    - media
  environment:
    - MYSQL_ROOT_PASSWORD=ItCydyatzix8
    - MYSQL_DATABASE=telemeta
    - MYSQL_USER=telemeta
    - MYSQL_PASSWORD=iuvIlkyisFit2

broker:
  image: redis

search:
  image: elasticsearch:1

app:
  build: .
  volumes:
    - ./app/:/srv/app
    - ./telemeta/:/srv/src/app/telemeta
  volumes_from:
    - media
  command: /bin/sh deploy/start_app.sh
  ports:
    - "9001:9000"
  expose:
    - "8000"
  links:
    - broker
    - db
    - search

worker:
  build: .
  volumes_from:
    - app
  command: /bin/sh deploy/celery_app.sh
  links:
    - broker
    - db

nginx:
  image: nginx
  ports:
    - "8000:80"
  volumes:
    - ./app/deploy/nginx-app.conf:/etc/nginx/conf.d/default.conf
    - ./var/log/nginx/:/var/log/nginx
  volumes_from:
    - media
  links:
    - app
    - phpmyadmin

phpmyadmin:
    image: nazarpc/phpmyadmin
    links:
      - db:mysql
